---
services:
  postgres:
    image: postgres:16
    network_mode: host
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - postgres:/var/lib/postgres

  backend:
    build: ./backend
    network_mode: host
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - 80:80

volumes:
  postgres:
